spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/management_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

cxf:
  path: /service


