version: '3.4'

services:
  pg_db:
    image: 'postgres:9.6.12-alpine'
    container_name: postgres_container
    environment:
      - DB_NAME=management_db
      - PGDATA=/var/lib/postgresql/data/management_db
      - POSTGRES_PASSWORD=123456
      - TABLEFUNC_SCHEMA=management
      - DBMIGRATION_USER=postgres
      - DBMIGRATION_PASS=123456
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    restart: always
